import { Customer } from './customer';

export const CUSTOMERS: Customer[] = [
  {
    id: 1,
    name: "John Pakistani",
    orderNumber: 1021,
    dateAndTime: new Date ("October 1, 2023 09:00:00"),
    items: {
      item1: {
        name: "Cat Food",
        brand: "Whiskas",
        weight: "3kg",
        type: "Dry Food",
        price: 20.00,
        quantity: 2,
      },
      vouchers: 0,
    },
    total: 0,
  },
  {
    id: 32,
    name: "John Pakistani",
    orderNumber: 1289,
    dateAndTime: new Date ("October 1, 2023 12:00:00"),
    items: {
      item1: {
        name: "Cat Food",
        brand: "Whiskas",
        weight: "3kg",
        type: "Dry Food",
        price: 20.00,
        quantity: 10,
      },
      vouchers: 0,
    },
    total: 0,
  },
  {
    id: 2,
    name: "Jane Smith",
    orderNumber: 1028,
    dateAndTime: new Date ("October 7, 2023 08:00:00"),
    items: {
      item1: {
        name: "Dog Treats",
        brand: "Milk-Bone",
        type: "Biscuits",
        price: 15.00,
        quantity: 1,
      },
      item2: {
        name: "Dog Leash",
        brand: "Flexi",
        type: "Retractable",
        price: 20.00,
        quantity: 1,
      },
      vouchers: 0,
    },
    total: 0,
  },
  {
    id: 3,
    name: "David Johnson",
    orderNumber: 1038,
    dateAndTime: new Date ("October 12, 2023 09:00:00"),
    items: {
      item1: {
        name: "Fish Tank",
        brand: "Aqueon",
        type: "Glass Aquarium",
        price: 100.00,
        quantity: 1,
      },
      item2: {
        name: "Fish Food",
        brand: "Tetra",
        type: "Flakes",
        price: 10.00,
        quantity: 1,
      },
      vouchers: 0,
    },
    total: 0,
  },
  {
    id: 4,
    name: "Linda Davis",
    orderNumber: 1039,
    dateAndTime: new Date ("October 15, 2023 09:00:00"),
    items: {
      item1: {
        name: "Bird Cage",
        brand: "Prevue Hendryx",
        type: "Round Roof",
        price: 50.00,
        quantity: 1,
      },
      vouchers: 0,
    },
    total: 0,
  },
  {
    id: 5,
    name: "Robert Wilson",
    orderNumber: 1045,
    dateAndTime: new Date ("October 18, 2023 09:00:00"),
    items: {
      item1: {
        name: "Hamster Wheel",
        brand: "Kaytee",
        type: "Exercise Wheel",
        price: 15.00,
        quantity: 2,
      },
      item2: {
        name: "Hamster Bedding",
        brand: "Carefresh",
        type: "Natural Paper",
        price: 5.00,
        quantity: 2,
      },
      vouchers: 0,
    },
    total: 0,
  },
  {
    id: 5,
    name: "Robert Wilson",
    orderNumber: 1045,
    dateAndTime: new Date ("October 18, 2023 09:00:00"),
    items: {
      item1: {
        name: "Hamster Wheel",
        brand: "Kaytee",
        type: "Exercise Wheel",
        price: 15.00,
        quantity: 2,
      },
      item2: {
        name: "Hamster Bedding",
        brand: "Carefresh",
        type: "Natural Paper",
        price: 5.00,
        quantity: 2,
      },
      vouchers: 0,
    },
    total: 0,
  },
  {
    id: 5,
    name: "Robert Wilson",
    orderNumber: 1045,
    dateAndTime: new Date ("October 10, 2023 09:00:00"),
    items: {
      item1: {
        name: "Hamster Wheel",
        brand: "Kaytee",
        type: "Exercise Wheel",
        price: 15.00,
        quantity: 2,
      },
      item2: {
        name: "Hamster Bedding",
        brand: "Carefresh",
        type: "Natural Paper",
        price: 5.00,
        quantity: 2,
      },
      vouchers: 0,
    },
    total: 0,
  },
  {
    id: 6,
    name: "Mary Lee",
    orderNumber: 1052,
    dateAndTime: new Date ("October 20, 2023 09:00:00"),
    items: {
      item1: {
        name: "Reptile Terrarium",
        brand: "Exo Terra",
        type: "Glass Terrarium",
        price: 150.00,
        quantity: 1,
      },
      vouchers: 0,
    },
    total: 0,
  },
  {
    id: 7,
    name: "William Miller",
    orderNumber: 1056,
    dateAndTime: new Date ("October 23, 2023 09:00:00"),
    items: {
      item1: {
        name: "Small Animal Cage",
        brand: "Ferplast",
        type: "Hamster Habitat",
        price: 60.00,
        quantity: 1,
      },
      item2: {
        name: "Small Animal Food",
        brand: "Oxbow",
        type: "Essentials",
        price: 20.00,
        quantity: 1,
      },
      vouchers: 0,
    },
    total: 0,
  },
  {
    id: 8,
    name: "Sarah Brown",
    orderNumber: 1058,
    dateAndTime: new Date ("October 25, 2023 09:00:00"),
    items: {
      item1: {
        name: "Cat Scratching Post",
        brand: "Go Pet Club",
        type: "Cat Tree",
        price: 60.00,
        quantity: 1,
      },
      vouchers: 0,
    },
    total: 0,
  },
  {
    id: 9,
    name: "Michael Jones",
    orderNumber: 1063,
    dateAndTime: new Date ("October 28, 2023 09:00:00"),
    items: {
      item1: {
        name: "Dog House",
        brand: "Suncast",
        type: "Outdoor Dog House",
        price: 120.00,
        quantity: 1,
      },
      vouchers: 0,
    },
    total: 0,
  },
  {
    id: 10,
    name: "Emily Harris",
    orderNumber: 1070,
    dateAndTime: new Date ("October 30, 2023 09:00:00"),
    items: {
      item1: {
        name: "Ferret Cage",
        brand: "Kaytee",
        type: "Multi-Level Cage",
        price: 70.00,
        quantity: 1,
      },
      item2: {
        name: "Ferret Food",
        brand: "Marshall",
        type: "Premium Diet",
        price: 15.00,
        quantity: 1,
      },
      vouchers: 0,
    },
    total: 0,
  },
  {
    id: 11,
    name: "Amanda Wilson",
    orderNumber: 1077,
    dateAndTime: new Date("October 5, 2023 09:00:00"),
    items: {
      item1: {
        name: "Cat Food",
        brand: "Hill's Science Diet",
        weight: "5kg",
        type: "Dry Food",
        price: 25.00,
        quantity: 3,
      },
      item2: {
        name: "Cat Litter",
        brand: "Arm & Hammer",
        type: "Clumping",
        price: 10.00,
        quantity: 3,
      },
      item3: {
        name: "Cat Toys",
        brand: "SmartyKat",
        type: "Feather Whirl",
        price: 8.00,
        quantity: 3,
      },
      item4: {
        name: "Cat Bed",
        brand: "Frisco",
        type: "Round",
        price: 15.00,
        quantity: 3,
      },
      vouchers: 0,
    },
    total: 0,
  },

  {
    id: 12,
    name: "Marlon Brando",
    orderNumber: 1077,
    dateAndTime: new Date("October 5, 2023 09:00:00"),
    items: {
      item1: {
        name: "Cat Food",
        brand: "Hill's Science Diet",
        weight: "5kg",
        type: "Dry Food",
        price: 25.00,
        quantity: 3,
      },
      item2: {
        name: "Cat Litter",
        brand: "Arm & Hammer",
        type: "Clumping",
        price: 10.00,
        quantity: 3,
      },
      item3: {
        name: "Cat Toys",
        brand: "SmartyKat",
        type: "Feather Whirl",
        price: 8.00,
        quantity: 3,
      },
      item4: {
        name: "Cat Bed",
        brand: "Frisco",
        type: "Round",
        price: 15.00,
        quantity: 3,
      },
      vouchers: 0,
    },
    total: 0,
  },

];

export default CUSTOMERS;    
